version: '3.4'

services:
  nginx:
    container_name: 'app_nginx'
    build: ./images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"

  php:
    container_name: 'app_php'
    build: ./images/php
    volumes:
      - ./lumen:/var/www
    working_dir: /var/www/public
    command: php-fpm
    links:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: AndEnbtvRU573dVEUqq5X8erpXYfGhFm
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: lumen
      DB_USERNAME: lumen
      DB_PASSWORD: secret

  db:
    container_name: 'app_db'
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./images/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumen
      MYSQL_PASSWORD: secret
